name:                biscuit-haskell
version:             0.1.0.0
github:              "githubuser/biscuit-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-libraries:
- biscuit_auth

extra-source-files:
- README.md
- ChangeLog.md
#c-sources:
#- csources/ristretto.h
#- csources/ristretto.c

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/biscuit-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring
- base64
- containers
- cryptonite
- either
- hex
- inline-c
- libsodium
- mtl
- cereal
- protobuf
- random
- text
- template-haskell
- th-lift-instances
- time
- primitive

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  biscuit-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - biscuit-haskell

tests:
  biscuit-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - biscuit-haskell
    - tasty
    - tasty-hunit
