name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: ["native-impl"]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cabal: ["3.4.0.0"]
        ghc: ["8.10.4"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Prepare environment
      run: .github/workflows/setup_ci_env.sh

    - name: Freeze
      run: |
        cabal freeze
 
    - uses: actions/cache@v2
      name: Cache ~/.cabal/store and .ghcup
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          .ghcup
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cabal configure --enable-tests --test-show-details=direct --disable-optimization
        cabal build -j all
    - name: Test
      run: cabal test all
