name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.10.3.0"]
        ghc: ["9.2.4", "9.4.8", "9.6.5", "9.8.2"]

    steps:
    - uses: actions/checkout@v3
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - name: Prepare environment
      run: .github/workflows/setup_ci_env.sh

    - name: Freeze
      run: |
        cabal freeze
 
    - uses: actions/cache@v3
      name: Cache ~/.cabal/store and .ghcup
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          .ghcup
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cp .cabal.project.local cabal.project.local
        cabal configure --enable-tests --test-show-details=direct --disable-optimization
        cabal build all
    - name: Test
      run: |
        cabal test all
